			<div class="box clearfix">
				<h1>Ajouter un document</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
				non diam eu consequat.</p>
				<br />
				<input type="file" />
			</div>
			<br /><br />
			<form>
				<fieldset>
					<div>
						<label>Titre</label>
						<input type="text" />
					</div>
					<br />
					<div>
						<label>Message</label>
						<input type="text" />
					</div>
					<br />
					<div>
						<label>Type</label>
						<select>
							<option>1</option>
							<option>2</option>
							<option>3</option>
						</select>
					</div>
					<br />
					<div>
						<label>Auteur</label>
						<input type="text" />
					</div>
					<br />
					<div>
						<label>Date Limite Réponse</label>
						<input type="text" />
					</div>
					<br />
					<div>
						<label>Classification</label>
						<input type="text" />
					</div>
					<br />
					<div>
						<label>Code Externe</label>
						<input type="text" />
					</div>
					<br />
					<div>
						<label>Message Usage Interne</label>
						<input type="text" />
					</div>
					<br />
					<div>
						<input type="button" value="Ajouter" />
						<input type="button" value="Annuler" />
					</div>					
				</fieldset>
			</form>