			<div class="box clearfix">
				<h1>Ajouter un document</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
				non diam eu consequat.</p>
				<br />
				<input type="file" name="uploaded_file"/>
			</div>
			<br /><br />
			<form action="index/addfile" method="post">
				<fieldset>
					<div>
						<label>Titre</label>
						<input type="text" name="titre"/>
					</div>
					<br />
					<div>
						<label>Objet du document</label>
						<input type="text" name="objet" />
					</div>
					<br />
					<div>
						<label>Type</label>
						<select>
							<option>Administratif</option>
							<option>Projet</option>
							<option>Divers</option>
						</select>
					</div>
					<br />
					<div>
						<label>Identifiant Auteur</label>
						<input type="number" name="id_author" />
					</div>
					<br />
					<div>
						<label>Date Limite Réponse</label>
						<input type="date" name="date_limite"/>
					</div>
					<br />
					<div>
						<label>Classification</label>
						<input type="number" name="classification" />
					</div>
					<br />
					<div>
						<label>Code Externe</label>
						<input type="text" name="code_externe"/>
					</div>
					<br />
					<div>
						<label>Message Usage Interne</label>
						<input type="text" />
					</div>
					<br />
					<div>
						<input type="button" value="Ajouter" />
						<input type="button" value="Annuler" />
					</div>					
				</fieldset>
			</form>