<?php 
	/*
	 * File : index.phtml
	* Author : Thomas Nguyen-huu
	* Created : 09/11/2013
	* Modified : 16/11/2013
	* 1.1 : Thomas Nguyen-huu - creation and modification
	* 1.2 : Mathilde de l'Hermuzière - modification
	* 1.3 : Hina Tufail - modification
	* 1.4 : Mathilde de l'Hermuzière - modification
	* 1.5 : Hina Tufail - modification - 20/11/2013
	* 
	* Action to display index of files
	*
	* Projet parapheur 2014
	*/
?> 			 <div class="box clearfix"> 
 				<div class="on-left">
					<h1><?php echo $this->number_doc; ?> documents à valider</h1>
 					<p>Veuillez sélectionner à l'aide des cases à cocher les documents que vous souhaitez
 						transférer sur tablette.
 						<?php echo $this->test;?></p> 
 				</div> 
 				<input class="blue-button on-right" type="button" value="Transférer" /> 
 			</div>
 			<div id="display-sign-success">
 				<p><?php echo $this->sucessMessage;?></p>
 			</div>
 			 <div id="display-sign-error">
 				<p><?php echo $this->errorMessage;?></p>
 			</div>
			<?php $i=0;?>
 			<div id="index"> 
 				<ul class="index-row"> 
 				<?php foreach($this->id_document as $id_document) : ?>
 					<li> 
	 					
	 					<a id="<?php $this->id_document[$i]?>" class="preview" onClick="<?php 
	 						$id= $this->id;
	 						Zend_Session::start();
	 						$sessioniddoc = new Zend_Session_Namespace('sessioniddoc');
	 						$sessioniddoc->id=$id;
	 					?>" href="<?php 
							echo $this->url(
					           		array(
									'controller' => 'viewer',
									'action'=>'index')
									)
						?> "> 
							<?php 
							?>
	 						<img src="img/icons/ico_pdf.png" alt="" /> 
	 					</a>
						 <a href="<?php 
							echo $this->url(
	 				           	array(
	 				           		'controller' => 'showPdf',
	 				           		'action'=>'showfile',
	 								'COURRIER_ID'=>$this->id_document[$i]),
	 				           		'default',
	 				        true)
							?>"> 
							<?php echo $this->titre[$i];?>
						</a>
						<p>Créé le : <?php echo $this->date[$i]; $i++;?></p><br/>
	 					<p><input type="checkbox" name="<?php echo $this->titre[$i];?>"></p>
						<?php if($i%5==0){?></ul><ul class ="index-row"><?php }?>
 					</li> 
 				<?php endforeach; ?>
 				</ul> 
				
 			</div>
						
