			<div class="box clearfix">
				<div class="on-left">
					<h1>8 documents à valider</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
					non diam eu consequat.</p>
				</div>
				<input class="blue-button on-right" type="button" value="Transférer" />
			</div>
			<div id="index">
				<ul class="index-row">
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
				</ul>
				<ul class="index-row">
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
				</ul>
				<ul class="index-row">
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
					<li>
						<a href="" class="preview">
							<img src="img/icons/ico_pdf.png" alt="" />
						</a>
						<a>Lorem ipsum dolor sit a...</a>
						<p>Mois JJ, AAAA</p>
					</li>
				</ul>
			</div>
