<?php

/*
 * File : imagick.phtml
* Author : Mathilde de l'Hermuzière
* Created : 09/11/2013
* Modified : 13/11/2013
* 1.1 :  Mathilde de l'Hermuzière - creation and modification
* 1.2 : Thomas Nguyen-huu - modification
* 1.3 :  Mathilde de l'Hermuzière - modification
* Action to use a flipbook
*
* Projet parapheur 2014
*/

// 	$fileName = '..\docs\debuter-avec-zend-framework.pdf';
	
// 	$pdf = new Zend_Pdf();
// 	$pdf = Zend_Pdf::load($fileName,null,true);
	
// 	$test=$pdf->pages[1];
	
 	//$im = new imagick($test); 
 	//$im->setImageColorspace(255); 
 	//$im->setResolution(300, 300);
 	//$im->setCompressionQuality(95); 
 	//$im->setImageFormat('jpeg'); 
 	//$im->writeImage('thumb.jpg'); 
 //	$im->clear(); 
// 	$im->destroy();
	
?>