<?php /*
 * Fichier : sign.phtml
* Auteur : Mathilde de l'Hermuzière
* Créé : 09/11/2013
* Modifié : 13/11/2013
* 1.1 :  Mathilde de l'Hermuzière - création et modification
* 1.2 :  Mathilde de l'Hermuzière - modification
* 
* Action d'ajout d'un document
*
* Projet parapheur 2014
*/?>

<h1>Ajouter un document</h1>
<p>Vous pouvez ajouter un document de votre bureau à notre application et l'envoyer à des destinataires.</p>
<br />

 <div id="display-sign-error">
 	<?php
		echo $this->errorMsg;
	?>
 </div>

<?php
	$this->form->setAction($this->url());
	echo $this->form; 
?>


<script type="text/javascript">
	$('#nav .n2 a').addClass('nav-sel');
</script>

