<?php /*
 * File : sign.phtml
* Author : Mathilde de l'Hermuzière
* Created : 09/11/2013
* Modified : 13/11/2013
* 1.1 :  Mathilde de l'Hermuzière - creation and modification
* 1.2 :  Mathilde de l'Hermuzière - modification
* 
* Action to add a file
*
* Projet parapheur 2014
*/?>

<h1>Ajouter un document</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
non diam eu consequat.</p>
<br />

<form enctype="multipart/form-data" action="/addafile/sign" method="POST">
    <input type="hidden" name="MAX_FILE_SIZE" value="100000" />
        Choose a file to upload:
        <input name="uploadedfile" type="file" />
        <br />
    <!-- <input type="submit" value="Upload File" /> -->
</form>

<?php
$this->form->setAction($this->url());
echo $this->form; 
?>


<script type="text/javascript">
	$('#nav .n2 a').addClass('nav-sel');
</script>

