<?php 
	/*
	 * File : test.phtml
	* Author : Hina Tufail
	* Created : 09/11/2013
	* Modified : 13/11/2013
	* 1.1 : Hina Tufail - creation
	* 1.2 : Thomas Nguyen-huu - modification
	* 1.3 : Mathilde de l'Hermuzière - modification
	* 1.4 : Hina Tufail
	* 
	* Action for test purposes - to be deleted with the associated Controller
	* test on the flipbook with a PDF
	*
	* Projet parapheur 2014
	*/
?>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  
 <?php echo $this->headScript()->prependFile($this->baseUrl().'/js/turn.js')
 							->prependFile($this->baseUrl().'/js/turn.min.js');?>
 							
 							  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/showfileStyle.css'); ?>

<body>

<div id="magazine">
	<div> Turn.js </div>
	<div> <img src="../../img/vacheprout.png"/> </div>
	<div> Page 2 </div>
	<div> Page 3 </div>
	<div> Page 4 </div>
	<div></div>

</div>

<script type="text/javascript">

        $(window).ready(function() {
                $('#magazine').turn({
                                                        display: 'double',
                                                        acceleration: true,
                                                        gradients: !$.isTouch,
                                                        elevation:50,
                                                        when: {
                                                                turned: function(e, page) {
                                                                        /*console.log('Current view: ', $(this).turn('view'));*/
                                                                }
                                                        }
                                                });
        });
        
        
        $(window).bind('keydown', function(e){
                
                if (e.keyCode==37)
                        $('#magazine').turn('previous');
                else if (e.keyCode==39)
                        $('#magazine').turn('next');
                        
        });

</script>

</body>
</html>



