<?php /*
	 * Fichier : index.phtml
	* Auteur : Hina Tufail
	* Créé : 14/12/2013
	* Modifié : 16/11/2013
	* 1.1 : Hina Tufail - création
	* 1.2 :  Clément Mouraud - impression
	* Action d'affichage de l'index des documents refusés
	*
	* Projet parapheur 2014
	*/?>
			<?php $i=0;?>
			<div class="box clearfix"> 
 				<div class="on-left">
					<h1>Documents refusés</h1>
					<p>Voici les documents soumis et qui ont été refusés. Le document est téléchargeable en cliquant dessus.</p> 
 				</div>
 				<a class="blue-button on-right" type="button" href="<?php echo $this->url(
																	 			           	array(
																							'controller' => 'Index',
																							'action'=>'index')
																							);?>"> Retour index </a>
  
 			</div>
 			<br/><br/>
 			<div id="index"> 
 				<ul class="index-row"> 
 				<?php foreach($this->id_document as $id_document) : ?>
 					<li> 
	 					
	 					<a id="<?php $this->id_document[$i]?>" class="preview" onClick="<?php 
	 						$id= $this->id;
	 					?>" href="<?php 
							echo $this->url(
					           		array(
									'controller' => 'ValidatedDocs',
									'action'=>'download',
									'COURRIER_ID'=>$this->id_document[$i])
									)
						?> "> 
							<?php 
							?>
	 						<img src="/img/icons/ico_pdf.png" alt="" /> 
	 					</a>
						 <a href="<?php 
							echo $this->url(
	 				           	array(
								'controller' => 'ValidatedDocs',
								'action'=>'download',
								'COURRIER_ID'=>$this->id_document[$i])
								)
							?>"> 
							<?php echo $this->titre[$i];?>
						</a>
						<p>Créé le : <?php echo $this->date[$i]; $i++;?></p><br/>
						<?php if($i%5 == 0){?></ul><ul class ="index-row"><?php }?>
 					</li> 
 				<?php endforeach; ?>
 				</ul> 
				
 			</div>
			<script type="text/javascript">
				$('#nav .n1 a').addClass('nav-sel');
			</script>