    <title>Signer le PDF</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/sketch.css'); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/sketch.js')
  								->prependFile($this->baseUrl().'/js/jquery.js')
  								->prependFile($this->baseUrl().'/js/canvas2image.js')
  								->prependFile($this->baseUrl().'/js/base64.js');?>

<br/>
<div class="tools">
  <a href="<?php 
			//Link to the controller displaying the PDF meta informations
			echo $this->url(
          	array(
          		'controller' => 'ShowPdf',
          		'action'=>'showfile'),
          		'default',
          true) 
			?>#colors_sketch" data-download="png" >Download</a>
 	
</div>

<canvas id="colors_sketch" 	 width="1000" height="600"></canvas>
<script type="text/javascript">
  $(function() {
    $.each(['#f00', '#ff0', '#0f0', '#0ff', '#00f', '#f0f', '#000', '#fff'], function() {
      $('#colors_demo .tools').append("<a href='#colors_sketch' data-color='" + this + "' style='width: 10px; background: " + this + ";'></a> ");
    });
    $.each([3, 5, 10, 15], function() {
      $('#colors_demo .tools').append("<a href='#colors_sketch' data-size='" + this + "' style='background: #ccc'>" + this + "</a> ");
    });
    $('#colors_sketch').sketch();
  });

  function redirect(){
	  var oCanvas = document.getElementById(colors_sketch);
	  Canvas2Image.saveAsPNG(oCanvas, false, 100, 100);  
	  
	  document.location.href="<?php 
			//Link to the controller displaying the PDF meta informations
			echo $this->url(
          	array(
          		'controller' => 'ShowPdf',
          		'action'=>'showfile'),
          		'default',
          true) 
			?>";
			
  }

  
</script>      