<?php echo $this->doctype()

/*
 * File : layout.phtml
* Author : Hina Tufail
* Created : 19/10/2013
* Modified : 03/11/2013
* 1.1 :  Hina Tufail - creation
* 1.2 : Clément Mouraud - modification
* 1.3 : Thomas Nguyen-huu - modification
*
* Layout that is displayed in every page, except if it is disabled in the controller associated to the action view
*
* Projet parapheur 2014
*/
?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Parapheur Numérique Application</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/reset.css')
  							  ->appendStylesheet($this->baseUrl().'/css/style.css'); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.10.3.js')
  								->prependFile($this->baseUrl().'/js/jquery-1.9.1.js');?>
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<div class="wrap">
				<ul id="nav">
					<li class="n1"><a href="<?php 
					echo $this->url(
		            	array(
		            		'controller' => 'index',
		            		'action'=>'index'),
		            		'default',
		            true) 
					?>">Index</a></li>
					<li class="n2"><a href="<?php 
					echo $this->url(
		            	array(
		            		'controller' => 'addafile',
		            		'action'=>'sign'),
		            		'default',
		            true) 
					?>">Ajouter</a></li>
					<li class="n3"><a href="<?php 
					echo $this->url(
		            	array(
		            		'controller' => 'admin',
		            		'action'=>'index'),
		            		'default',
		            true) 
					?>">Administration</a></li>
					<li class="n4"><a href="<?php 
					echo $this->url(
		            	array(
		            		'controller' => 'admin',
		            		'action'=>'diagnostic'),
		            		'default',
		            true) 
					?>">Diagnostic</a></li>
				</ul>
				<div class="search-box">
					<label>Rechercher</label>
					<input type="text" name="search" value = "">
				</div>
			</div>
		</div>
		<div id="content" class="wrap clearfix">
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
	<div id="footer">
		<div class="wrap">
			<ul class="l-foot">
				<li><a href="">Lien 1</a></li>
				<li>|</li>
				<li><a href="">Lien 2</a></li>
				<li>|</li>
				<li><a href="">Lien 3</a></li>
			</ul>
			<p class="l-note">
				Lorem ipsum dolor sit amet
			</p>
		</div>
	</div>
</body>
</html>