<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Parapheur Application</title>
  <?php echo $this->headLink()->appendStylesheet('../../css/global.css') ?>
  <?php //echo $this->jQuery();?>
</head>

<body>

<div id="header">
    <div id="header-logo">
        <b>Projet Parapheur !! :) </b>
    </div>
    <div id="header-navigation">
        <a href="<?php echo $this->url(
            array('controller'=>'test'),
            'default',
            true) ?>">test section (blablabla)</a>
    </div>
</div>

<?php echo $this->layout()->content; ?>

</body>
</html>