<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Parapheur Application</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/reset.css')
  ->appendStylesheet($this->baseUrl().'/css/style.css'); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.10.3.js')
  								->prependFile($this->baseUrl().'/js/jquery-1.9.1.js');?>
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<div class="wrap">
				<ul id="nav">
					<li><a class="nav-sel" href="<?php 
					echo $this->url(
		            	array(
		            		'controller' => 'index',
		            		'action'=>'index'),
		            		'default',
		            true) 
					?>">Index</a></li>
					<li><a href="<?php 
					echo $this->url(
		            	array(
		            		'controller' => 'index',
		            		'action'=>'addfile'),
		            		'default',
		            true) 
					?>">Ajouter</a></li>
					<li><a href="<?php 
					echo $this->url(
		            	array(
		            		'controller' => 'admin',
		            		'action'=>'index'),
		            		'default',
		            true) 
					?>">Administration</a></li>
					<li><a href="<?php 
					echo $this->url(
		            	array(
		            		'controller' => 'admin',
		            		'action'=>'diagnostic'),
		            		'default',
		            true) 
					?>">Diagnostique</a></li>
				</ul>
				<div class="search-box">
					<label>Rechercher</label>
					<input type="text" name="search" />
				</div>
			</div>
		</div>
		<div id="content" class="wrap clearfix">
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
	<div id="footer">
		<div class="wrap">
			<ul class="l-foot">
				<li><a href="">Lien 1</a></li>
				<li>|</li>
				<li><a href="">Lien 2</a></li>
				<li>|</li>
				<li><a href="">Lien 3</a></li>
			</ul>
			<p class="l-note">
				Lorem ipsum dolor sit amet
			</p>
		</div>
	</div>
</body>
</html>