<?php 
	/*
	 * File : commentPopup.phtml
	* Author : Fanny Seiler
	* Created : 09/11/2013
	* 1.1 : Fanny Seiler - creation
	* 
	* Action pop up for commenting a document
	*
	* Projet parapheur 2014
	*/
?>

<div id="comment_doc" class="popup_block">
		<a class="close" href="#">
			<img class="btn_close" alt="" src="../../img/icons/close_pop.png"></img>
		</a>
		<h1>Commentaires</h1>
		<div class="write_comment">
			<select>
				<option>Projet</option>
				<option>Document</option>
			</select>
			<textarea  class="on-right"></textarea>
			<a href="#"><input class="blue-button on-right" type="button" value="Commenter" /></a>
		</div>
		<div class="all_comments">
			<ul>
				<li>
					<div>
						<div class="author on-left">Auteur</div>
						<div class="on-left">&nbsp•&nbsp</div>
						<div class="on-left">date</div>
					</div></br>	
					<div class="comment-inner">
						<div class="quote on-left"><img src="../../img/pop/quote_start.png"></img></div>
						<div class="comment">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
						</div>
						<div class="quote on-right on-bottom"><img src="../../img/pop/quote_end.png"></img></div>
					</div>
				</li>
				<li>
					<div>
						<div class="author on-left">Auteur</div>
						<div class="on-left">&nbsp•&nbsp</div>
						<div class="on-left">date</div>
					</div></br>	
					<div class="comment-inner">
						<div class="quote on-left"><img src="../../img/pop/quote_start.png"></img></div>
						<div class="comment">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
						</div>
						<div class="quote on-right on-bottom"><img src="../../img/pop/quote_end.png"></img></div>
					</div>
				</li>
			</ul>
		</div>
	</div>
