<?php 
	/*
	 * File : metainfoPopup.phtml
	* Author : Fanny Seiler
	* Created : 09/11/2013
	* 1.1 : Fanny Seiler - creation
	* 
	* Action pop up for meta informations
	*
	* Projet parapheur 2014
	*/
?>

<div id="info_doc" class="popup_block">
		<a class="close" href="#">
			<img class="btn_close" alt="" src="../../img/icons/close_pop.png"></img>
		</a>
		<h1>Informations sur le document</h1>
		<p>Voici les méta-informations du document :</p>
		<div class="informations">
			<div class="on-left">
				<ul>
					<li>Titre :</li>
					<li>Auteur :</li>
					<li>Date de création :</li>
					<li>Date d'expédition :</li>
					<li>Date limite de réponse :</li>
					<li>Destinataires :</li>
				</ul>
			</div>	
			<div class="on-right">
				</ul>
				<ul>
					<li>Priorité :</li>
					<li>Classification :</li>
					<li>Type :</li>
					<li>Code externe :</li>
					<li>Groupe créateur :</li>
					<li>Dernière modification :</li>
				</ul>
			</div>	
		</div>
	</div>