<?php
/*
 * File : showfile.phtml
* Author : Hina Tufail
* Created : 19/10/2013
* Modified : 16/11/2013
* 1.1 :  Hina Tufail - creation
* 1.2 : Clément Mouraud - modification
* 1.3 : Hina Tufail - modification
* 1.4 : Clément Mouraud - modification
* 1.5 : Mathilde de l'Hermuzière - modification
* 1.6 : Hina Tufail - modification
* 1.7 : Clément Mouraud - modification
* 1.8 : Hina Tufail - modification
* 1.9 : Hina Tufail - modification
*
* Action file for doing action on a PDF document
*
* Projet parapheur 2014
*/
?>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
 <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/reset.css')
  							  ->appendStylesheet($this->baseUrl().'/css/style.css')
  							  ->appendStylesheet($this->baseUrl().'/css/showfileStyle.css')
							  ->appendStylesheet($this->baseUrl().'/css/viewer.css')
							  ->appendStylesheet($this->baseUrl().'/css/book.css'); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl().'/js/custom.js')
 							->prependFile($this->baseUrl().'/js/jquery-1.9.1.js');?>	
<body>

		<!-- Side menu : displays info, print, export icons -->
		<div id="sidePDFMenu">
			<!-- Meta info icon -->
		    <br/><br/><a href="#" data-width="720" data-rel="info_doc" class="poplight"><img src='../../../img/icons/ico_meta.png' alt='icone info image'/></a>
		    <!-- Print icon -->
		    <br/><br/><a href=""><img src='../../../img/icons/ico_print.png' alt='icone imprimante image'/></a>
		    <!-- Download icon -->
		    <br/><br/><a href="" id="telechargerIcone"><img src='../../../img/icons/ico_download.png' alt='icone télécharger image'/></a>   
			<!-- Export icon -->
			<br/><br/><a href=""><img src='../../../img/icons/ico_transfertTab.png' alt='icone transférer sur tablette image'/></a>
		</div>
		
		<!-- PDF link file -->
		<div id="PDFlinkfile">
		            <object data="<?php //echo $this->url(array('controller' => 'ShowPdf','action'=>'index'),'default',true) ?>" type="application/pdf" id="pdfApp" width="100%" height="100%">
								  <p>Il semblerait que vous n'ayez pas de plugin PDF pour ce navigateur
								  Pas de problèmes...vous pouvez <a href="<?php //echo $this->url(array('controller' => 'ShowPdf','action'=>'index'),'default',true) ?>">cliquer ici pour
								  télécharger le fichier PDF.</a></p>
					</object>
		</div>
		
		<!-- Bottom menu : comment, zoom, dezoom, first, last, previous, next pages, validate and refuse icons  -->
		<div id="bottomPDFMenu">
		<a href="#" data-width="720" data-rel="comment_doc" class="poplight"><img src='../../../img/icons/ico_com.png' alt='icone ajout de commentaire image'/></a>
		
		<a href="" id="zoomIcone"><img src='../../../img/icons/ico_plus.png' alt='icone zoom + image'/></a>
		<a href="" id="dezoomIcone"><img src='../../../img/icons/ico_moins.png' alt='icone zoom - image'/></a>
		
		<a href="" id="premierePageIcone"><img src='../../../img/icons/ico_firstPage.png' alt='icone première page image'/></a>
		<a href="" id="precedentePageIcone"><img src='../../../img/icons/ico_previousPage.png' alt='icone page precedente image'/></a>
		<a href="" id="suivantePageIcone"><img src='../../../img/icons/ico_nextPage.png' alt='icone page suivante image'/></a>
		<a href="" id="dernierePageIcone"><img src='../../../img/icons/ico_lastPage.png' alt='icone dernière page image'/></a>
		
		<a href="<?php 	echo $this->url(array('controller' => 'Index',
					           		'action'=>'index'),
					            		'default', true) ?>" id="pageAccueil"><img src='../../../img/icons/ico_home.png' alt='icone page accueil image'/></a>
		<a href="<?php 	echo $this->url(array('controller' => 'ShowPdf',
					            		'action'=>'signpdf'),
					            		'default', true) ?>" id="SignerIcone"><img src='../../../img/icons/ico_sign.png' alt='icone signer image'/></a>
		
		<!--Liens vers les popup : valider et refuser le document -->
		<a href="#" id="validateBtn" data-width="720" data-rel="validate_doc" class="poplight"><img src='../../../img/icons/ico_val.png' alt='icone valider document'/></a>
		<a href="#" id="refuseBtn" data-width="720" data-rel="refuse_doc" class="poplight"><img src='../../../img/icons/ico_refus.png' alt='icone refus document'/></a>

		</div>
		
<!--POPUP DEBUT -->
	
	<!--Validate Document -->
	<?php include ('validatePopup.phtml'); ?>
	
	<!--Refuse Document -->
	<?php include('refusePopup.phtml')?>
	
	<!--Comment Document -->
	<?php // include('commentPopup.phtml')?>
	<?php 
	/*
	 * File : commentPopup.phtml
	* Author : Fanny Seiler
	* Created : 09/11/2013
	* 1.1 : Fanny Seiler - creation
	* 
	* Action pop up for commenting a document
	*
	* Projet parapheur 2014
	*/
	?>

	<div id="comment_doc" class="popup_block">
		<a class="close" href="#">
			<img class="btn_close" alt="" src="../../img/icons/close_pop.png"></img>
		</a>
		<h1>Commentaires</h1>
		<div class="write_comment">
			<select>
				<option>Projet</option>
				<option>Document</option>
			</select>
			<textarea  class="on-right"></textarea>
			<a href="#"><input class="blue-button on-right" type="button" value="Commenter" /></a>
		</div>
		<?php $i=0;?>
		<div class="all_comments">
			<?php foreach($this->id_comment as $id_comment) : ?>
			<ul>
				<li>
					<div>
						<div class="author on-left"><?php echo $this->id_author[$i]; ?></div>
						<div class="on-left">&nbsp•&nbsp</div>
						<div class="on-left"><?php echo $this->date[$i]; ?></div>
					</div><br />	
					<div class="comment-inner">
						<div class="quote on-left"><img src="../../img/pop/quote_start.png"></img></div>
						<div class="comment"><?php echo $this->contenu[$i]; $i++; ?></div>
						<div class="quote on-right on-bottom"><img src="../../img/pop/quote_end.png"></img></div>
					</div>
				</li>
			</ul>
			<?php endforeach; ?>
		</div>
	</div>
	
	<!--Display Document Informations -->
	<?php include('metainfoPopup.phtml')?>
	
	<div id="popup_fade"></div>
	
<!--POPUP FIN -->
		
</body>