    <title>Signer le PDF</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/sketch.css'); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/sketch.js')
  								->prependFile($this->baseUrl().'/js/jquery.js')
  								->prependFile($this->baseUrl().'/js/canvas2image.js')
  								->prependFile($this->baseUrl().'/js/base64.js');?>

<br/>
<div class="tools">
<!--  data-download="png" -->
  <a href="#colors_sketch" data-download="png" onClick='createPNGButton();'>Download</a> 	
</div>

<canvas id="colors_sketch" 	 width="1000" height="600"></canvas>

<script type="text/javascript">
  $(function() {
    $.each(['#f00', '#ff0', '#0f0', '#0ff', '#00f', '#f0f', '#000', '#fff'], function() {
      $('#colors_demo .tools').append("<a href='#colors_sketch' data-color='" + this + "' style='width: 10px; background: " + this + ";'></a> ");
    });
    $.each([3, 5, 10, 15], function() {
      $('#colors_demo .tools').append("<a href='#colors_sketch' data-size='" + this + "' style='background: #ccc'>" + this + "</a> ");
    });
    $('#colors_sketch').sketch();
  });

  function redirect(){
	  var oCanvas = document.getElementById("colors_sketch"); 
	  Canvas2Image.saveAsPNG(oCanvas);  
	  document.location.href="<?php 
			//Link to the controller displaying the PDF meta informations
			echo $this->url(
          	array(
          		'controller' => 'ShowPdf',
          		'action'=>'showfile'),
          		'default',
          true) 
			?>";
			
  }

  function createPNGButton( ) {
	  /*var canvasData = testCanvas.toDataURL("image/png"); 
	  var ajax = new XMLHttpRequest();
	  ajax.open("POST",'ShowPdfController/showfile.phtml',false);
	  ajax.setRequestHeader('Content-Type', 'application/upload');
	  ajax.send(canvasData);*/
	  
	  var canvas = document.getElementById("colors_sketch"); 
	  var dataURL = canvas.toDataURL();
	  
	  // Get our file
		/*var file= dataURLtoBlob(dataURL);
		// Create new form data
		var fd = new FormData();*/
		// Append our Canvas image file to the form data
		//fd.append("sktech", file);
		// And send it
		/*$.ajax({
		   url: "showfile",
		   type: "POST",
		   data: fd,
		   processData: false,
		   contentType: false,
		}).done(function(respond){
		  alert(respond);
		});
		
		$.ajax({
		  type: "POST",
		  url: "showfile.phtml",
		  data: {image: dataURL}
		}).done(function( respond ) {
		 alert(respond);
		});
*/
	  
	  
	 }

  
</script>      