<?php
/*
 * File : signpdf.phtml
* Author : Hina Tufail
* Created : 19/10/2013
* Modified : 16/11/2013
* 1.1 :  Hina Tufail - creation
* 1.2 : Clément Mouraud - modification
* 1.3 : Hina Tufail - modification
* 1.4 : Clément Mouraud - modification
* 1.5 : Mathilde de l'Hermuzière - modification
* 1.6 : Hina Tufail - modification
* 1.7 : Clément Mouraud - modification
* 1.8 : Hina Tufail - modification
* 1.9 : Hina Tufail - modification
*
* Action file for signing and sending the signature to a PDF document
*
* Projet parapheur 2014
*/
?>

<title>Signer le PDF</title>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/sketch.css'); ?>
  <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/sketch.js')
  								->prependFile($this->baseUrl().'/js/jquery.js')
  								->prependFile($this->baseUrl().'/js/canvas2image.js')
  								->prependFile($this->baseUrl().'/js/base64.js');?>

<br/>
<div class="tools">
<!--  data-download="png" -->
  <a href="<?php echo $this->url(array('controller' => 'ShowPdf','action'=>'showfile'),'default',true) ?>" data-download="png" onClick='createPNGButton();'>Download</a> 	
</div>

<img src="" id="company_logo"/>
<canvas id="colors_sketch" 	 width="500" height="500"></canvas>

<script type="text/javascript">
  $(function() {
    $.each(['#f00', '#ff0', '#0f0', '#0ff', '#00f', '#f0f', '#000', '#fff'], function() {
      $('#colors_demo .tools').append("<a href='#colors_sketch' data-color='" + this + "' style='width: 10px; background: " + this + ";'></a> ");
    });
    $.each([3, 5, 10, 15], function() {
      $('#colors_demo .tools').append("<a href='#colors_sketch' data-size='" + this + "' style='background: #ccc'>" + this + "</a> ");
    });
    $('#colors_sketch').sketch();
  });

  function createPNGButton( ) {

	  var canvas = document.getElementById("colors_sketch"); 
      var strdata = canvas.toDataURL("image/png");

    $.ajax({
	 type: "POST",                                                  
	   url: "index",                     
	  data: "&data="+strdata,
	  success: function(arrResult) {
			//do something
			alert("success");
		  }
		});	  
	 }
</script>      