<?php 
	/*
	 * File : validatePopup.phtml
	* Author : Fanny Seiler
	* Created : 09/11/2013
	* 1.1 : Fanny Seiler - creation
	* 
	* Action pop up for validating a document
	*
	* Projet parapheur 2014
	*/
?>
<div id="validate_doc" class="popup_block">
			<a class="close" href="#">
				<img class="btn_close" alt="" src="../../img/icons/close_pop.png"></img>
			</a>
			<h1>Valider le document</h1>
			<p>Pour envoyer le document dans le workflow, cliquez sur le bouton valider. Une fois validé, le document ne pourra plus 				être modifié.</p>
			<a href="#"><input class="green-button on-right" type="button" value="Valider" onclick="validate();" /></a>
</div>
		
<script type="text/javascript">
 
  function validate() {
      var strdata = 'valid';

    $.ajax({
	 type: "POST",                                                  
	   url: "validatePopup",                     
	  data: "&data="+strdata,
	  success: function(arrResult) {
			//do something
			alert("success");
		  }
		});	  
	 }
</script>    