<div id="validate_doc" class="popup_block">
			<a class="close" href="#">
				<img class="btn_close" alt="" src="../../img/icons/close_pop.png"></img>
			</a>
			<h1>Valider le document</h1>
			<p>Pour envoyer le document dans le workflow, cliquez sur le bouton valider. Une fois validé, le document ne pourra plus 				être modifié.</p>
			<a href="#"><input class="green-button on-right" type="button" value="Valider" /></a>
</div>
		
