<h1>Informations sur le document : <?php echo $this->meta['Title']?></h1>


<?php

echo "Chemin : ".$this->file."<br/>"; 
echo "Titre : ".$this->meta['Title']."<br/>";
echo "Auteur : ".$this->meta['Author']."<br/>";
echo "Sujet : ".$this->meta['Subject']."<br/>";
echo "Mots clés : ".$this->meta['Keywords']."<br/>";
echo "Créateur : ".$this->meta['Creator']."<br/>";
echo "Producteur : ".$this->meta['Producer']."<br/>";
echo "Date de création : ".$this->meta['CreationDate']."<br/>";