			<div class="box">
				<h1>Diagnostic</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
				non diam eu consequat.</p>
			</div>
			<div id="box-test">
				<div class="box clearfix">
					<div class="on-left">
						<h1>Test connexion base de données</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
						non diam eu consequat.</p>
					</div>
					<input class="blue-button on-right" type="button" value="Vérifier" />
				</div>
				<div class="box clearfix">
					<div class="on-left">
						<h1>Test synchronisation tablette</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
						non diam eu consequat.</p>
					</div>
					<input class="blue-button on-right" type="button" value="Vérifier" />
				</div>
				<div class="box clearfix">
					<div class="on-left">
						<h1>Test accès serveur</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
						non diam eu consequat.</p>
					</div>
					<input class="blue-button on-right" type="button" value="Vérifier" />
				</div>
				<div class="box clearfix">
					<div class="on-left">
						<h1>Test web services</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
						non diam eu consequat.</p>
					</div>
					<input class="blue-button on-right" type="button" value="Vérifier" />
				</div>
			</div>