<?php 
	/*
	 * Fichier : diagnostic.phtml
	* Auteur : Thomas Nguyen-huu
	* Créé : 09/11/2013
	* Modifié : 13/11/2013
	* 1.1 :  Thomas Nguyen-huu - création et modification
	* 
	* Action pour les diagnostics
	*
	* Projet parapheur 2014
	*/
?>

<div class="box">
				<h1>Diagnostic</h1>
				<p>Testez vos connexions à la base de données, au serveur et aux tablettes.</p>
			</div>
			<div id="box-test">
				<div class="box clearfix">
					<div class="on-left">
						<h1>Test connexion base de données</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
						non diam eu consequat.</p>
					</div>
					<input class="blue-button on-right" type="button" value="Vérifier" onClick="alert('En cours d\'implementation!')" />
				</div>
				<div class="box clearfix">
					<div class="on-left">
						<h1>Test synchronisation tablette</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
						non diam eu consequat.</p>
					</div>
					<input class="blue-button on-right" type="button" value="Vérifier" onClick="alert('En cours d\'implementation!')" />
				</div>
				<div class="box clearfix">
					<div class="on-left">
						<h1>Test accès serveur</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
						non diam eu consequat.</p>
					</div>
					<input class="blue-button on-right" type="button" value="Vérifier" onClick="alert('En cours d\'implementation!')"/>
				</div>
			</div>
			
			<script type="text/javascript">
				$('#nav .n4 a').addClass('nav-sel');
			</script>