<?php 
	/*
	 * File : index.phtml
	* Author : Thomas Nguyen-huu
	* Created : 09/11/2013
	* Modified : 13/11/2013
	* 1.1 :  Thomas Nguyen-huu - creation and modification
	* 
	* Action to render diagnostics and administrate tablets, see which tablet has documents transfered, when it was synchronized
	*
	* Projet parapheur 2014
	*/
?>

<div class="box">
				<h1>Administration Tablettes</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
				non diam eu consequat.</p>
			</div>
			<div id="tablet-list">
				<h3>Tablette NEXUS 3024 Z</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette SAMSUSNG 450</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Hina</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Fanny</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Mathilde</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
			</div>
			<script type="text/javascript">
				$(function() {
					$( '#tablet-list' ).accordion({
						heightStyle: 'content'
					});
				});
				
				$('#nav .n3 a').addClass('nav-sel');
			</script>