<?php 
	/*
	 * Fichier : diagnostic.phtml
	* Auteur : Thomas Nguyen-huu
	* Créé : 09/11/2013
	* Modifié : 13/11/2013
	* 1.1 :  Thomas Nguyen-huu - création et modification
	* 
	* Action pour les diagnostics, poru administrer les tablettes
	*
	* Projet parapheur 2014
	*/http://parapheur/admin
?>

<div class="box">
				<h1>Administration Tablettes</h1>
				<p>Voici toutes les tablettes qui se sont connectées à notre application Parapheur et les documents contenus.</p>
			</div>
			<div id="tablet-list">
				<h3>Tablette NEXUS 3024 Z</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette SAMSUSNG 450</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Hina</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Fanny</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Mathilde</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
			</div>
			<script type="text/javascript">
				$(function() {
					$( '#tablet-list' ).accordion({
						heightStyle: 'content'
					});
				});
				
				$('#nav .n3 a').addClass('nav-sel');
			</script>