			<div class="box">
				<h1>Administration Tablettes</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt 
				non diam eu consequat.</p>
			</div>
			<div id="tablet-list">
				<h3>Tablette NEXUS 3024 Z</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette SAMSUSNG 450</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Hina</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Fanny</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
				<h3>Tablette de Mathilde</h3>
				<ul>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Document-NOM-VV-AAAAMMJJ.pdf</li>
					<li>Synchronisée le : DD - MM - AAAA</li>
				</ul>
			</div>
			<script>
				$(function() {
					$( "#tablet-list" ).accordion({
						heightStyle: "content"
					});
				});
			</script>