<?php

/*
 * Fichier : index.phtml
* Auteur : Mathilde de l'Hermuzière
* Créé : 09/11/2013
* Modifié : 13/11/2013
* 1.1 : Mathilde de l'Hermuzière - création and modification
* 1.2 : Thomas Nguyen-huu - modification
* 1.3 : Mathilde de l'Hermuzière - modification
* 1.4 : Mathilde de l'Hermuziere - ajout de dynamisme
* 1.5 : Thomas Nguyen-huu - flipbook
* 1.6 : Mathilde de l'Hermuzière - flipbook
* 1.5 : Hina Tufail : flipbook, paramètres et signature
* Action d'utilisation du flipbook
*
* Projet parapheur 2014
*/
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>PDF Flip Book</title>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/reset.css')
  								->appendStylesheet($this->baseUrl().'/css/flip.css')
								->appendStylesheet($this->baseUrl().'/css/popupStyle.css')
								->appendStylesheet($this->baseUrl().'/css/sketch.css'); ?>
  	<?php echo $this->headScript()->appendFile($this->baseUrl().'/js/turn.js')
  							      ->appendFile($this->baseUrl().'/js/compatibility.js')
  								  ->appendFile($this->baseUrl().'/js/l10n.js')
  								  ->appendFile($this->baseUrl().'/js/pdf.js')
  								  ->appendFile($this->baseUrl().'/js/viewer.js')
  								  ->appendScript('pdf_file="'.$this->pdfurl.'";')
  								  ->appendScript('pdf_title="'.$this->titre.'";')
  								  ->appendFile($this->baseUrl().'/js/sketch.js')
  								  ->appendFile($this->baseUrl().'/js/custom.js')
 								  ->prependFile($this->baseUrl().'/js/jquery-1.9.1.js');?>
 </head>
 
<body>

	<div id="loadingBox">
		<div id="loading" data-l10n-args="{'percent': 0}" data-l10n-id="loading">Loading... 0%</div>
		<div id="loadingBar">
			<div class="progress"></div>
		</div>
	</div>
	<div id="flip-book">
		<div id="viewer"></div>
	</div>
	<div id="side-bar">
		<ul>
			<li>
				<!-- Meta info icon -->
				<br/><br/><a title="Meta-Informations" class="btn-meta poplight" href="#" data-width="720" data-rel="info_doc"></a>
			</li>
			<li>
				<!-- Print icon -->
				<a id="print" title="Imprimer" class="btn-print" type="button" onclick="window.print()" ></a>
			</li>
			<li>
				<!-- Download icon -->
				<a id="download" title="Telecharger" class="btn-download" type="button" href="<?php
											echo $this->url(array(
												'controller' => 'Viewer',
					           					'action'=>'download',
												'COURRIER_ID'=>$this->id_document),
					            				'default', true)?>"></a>
			</li>
			<li>
				<!-- Export icon -->
				<a id="export" title="Exporter Tablette" class="btn-export" href="#" type="button" onClick="alert('En cours d\'implementation!')"></a>			
			</li>
			<li>
				<a href="#" data-width="720" class="btn-add-person poplight" data-rel="addperson_doc"></a>
			</li>
		</ul>
	</div>
	<div id="tool-bar">
		<div class="tool-left">
			<a href="#" data-width="720" Title="Commenter/Commentaires" data-rel="comment_doc" class="btn-comment poplight"></a>
		</div>
		<ul>
			<li>
				<input class="btn-zoomin" title="Zoomer" type="button" onclick="PDFView.zoomIn();">
			</li>
			<li>
				<input class="btn-zoomout" title="Dezoomer" type="button" onclick="PDFView.zoomOut();">
			</li>
			<li>
				<input id="go-first" title="Premiere Page" class="btn-gofirst"  type="button" onclick="PDFView.page = 1">
			</li>
			<li>
				<input id="previous" title="Page Precedente" class="btn-previous"  type="button" onclick="PDFView.page--">
			</li>
			<li class="page-cur">
				<input id="pageNumber" type="text" value="1" onchange="PDFView.page = this.value;" disabled="true">
				<span id="numPages"></span>
			</li>
			<li>
				<input id="next" title="Page Suivante" class="btn-next" type="button" onclick="PDFView.page++">
			</li>
			<li>
				<input id="go-last" title="Derniere Page" class="btn-golast"  type="button" onclick="PDFView.page = PDFView.pages.length">
			</li>
			<li>
				<a class="btn-home" title="Retour Page d'Accueil" href="<?php 	
											echo $this->url(array(
												'controller' => 'Index',
					           					'action'=>'index'),
					            				'default', true) ?>" 
					            				class=""></a>
			</li>
		</ul>		
		<div class="tool-right">
			<a title="Signer Document" href="#" id="SignerIcone" data-width="720" data-rel="sign_doc" class="btn-sign poplight"></a>
			<!--Liens vers les popup : valider et refuser le document -->
			<a title="Valider Document" href="#" id="validateBtn" data-width="720" data-rel="validate_doc" class="btn-valid poplight"></a>
			<a title="Refuser Document" href="#" id="refuseBtn" data-width="720" data-rel="refuse_doc" class="btn-invalid poplight"></a>
			
		</div>
		<select id="scaleSelect" onchange="PDFView.parseScale(this.value);" style="display:none;">
			<option id="pageAutoOption" value="auto">Automatic Zoom</option>
			<option id="customScaleOption" value="custom"></option>
		</select>
	</div>
	
<!--POPUP DEBUT -->
	<!--Display Document Informations -->
	<?php include('metainfoPopup.phtml')?>
	
	<!--Comment Document -->
	<?php include('commentpopup.phtml')?>
		
	<!--Validate Document -->
	<?php include ('validatePopup.phtml'); ?>
	
	<!--Refuse Document -->
	<?php include('refusePopup.phtml')?>
	
	<!--Add person to Document -->
	<?php include('addpersonpopup.phtml')?>
	
	<!-- Sign a document -->
	<?php include('signpdf.phtml')?>
	
	<div id="popup_fade"></div>
	
<!--POPUP FIN -->
		
</body>
</html>