<?php 
	/*
	 * File : refusePopup.phtml
	* Auteur : Fanny Seiler
	* Créé : 09/11/2013
	* 1.1 : Fanny Seiler - création
	* 1.2 : Hina Tufail - modification
	* 
	* Action pop up pour le refus d'un document
	*
	* Projet parapheur 2014
	*/
?>

	<div id="refuse_doc" class="popup_block">
		<a class="close" href="#">
			<img class="btn_close" alt="" src="../../../../img/icons/close_pop.png"></img>
		</a>
		<h1>Refuser le document</h1>
		<p>Si vous souhaitez retourner le document à son destinataire, cliquez sur le bouton refuser.</p>
		<div class="popup_message on-left"><h2>Message</h2></div>
		
		<?php
			$this->refuseForm->setAction($this->url(array('controller' => 'Viewer','action'=>'refusepdf','COURRIER_ID' => $this->id_document),'default',true));
			echo $this->refuseForm; 
		?>
	</div>
		
