<?php 
	/*
	 * Fichier : validatePopup.phtml
	* Auteur : Fanny Seiler
	* Créé : 09/11/2013
	* 1.1 : Fanny Seiler - création
	* 1.2 : Hina Tufail - modification et test de la base de données - 18/11/2013
	* 
	* Action pop up poru la validation d'un document
	*
	* Projet parapheur 2014
	*/
?>
<div id="validate_doc" class="popup_block">
			<a class="close" href="#">
				<img class="btn_close" alt="" src="../../../../img/icons/close_pop.png"></img>
			</a>
			<h1>Valider le document</h1>
			<p>Pour envoyer le document dans le workflow, cliquez sur le bouton valider. Une fois validé, le document ne pourra plus 				être modifié.</p>
			<?php
			$this->validateForm->setAction($this->url(array('controller' => 'Viewer','action'=>'validatepdf'),'default',true));
			echo $this->validateForm; 
			?>
</div> 